default_platform(:ios)

platform :ios do

  desc "Assemble IPA file for simulator"
  lane :assembleDebug do |options|
        xcodeproj = options[:xcodeproj]
        scheme = options[:scheme]
        deviceId = options[:deviceId]
        build_app(
          project: "#{xcodeproj}",
          scheme: "#{scheme}",
          configuration: "Debug",
          skip_codesigning: false,
          skip_package_ipa: true,
          skip_archive: true,
          destination: "id=#{deviceId}",
          derived_data_path: "./build"
        )
    end
end

