package com.tezov.tuucho.core.data.parser.rectifier.id

import com.tezov.tuucho.core.data.di.MaterialRectifierModule.Name
import com.tezov.tuucho.core.data.parser._system.IdGenerator
import com.tezov.tuucho.core.data.parser._system.MatcherProtocol
import com.tezov.tuucho.core.data.parser.rectifier.Rectifier
import com.tezov.tuucho.core.domain._system.JsonElementPath
import com.tezov.tuucho.core.domain._system.find
import com.tezov.tuucho.core.domain._system.stringOrNull
import com.tezov.tuucho.core.domain.schema.SymbolData
import com.tezov.tuucho.core.domain.schema.common.IdSchema.Companion.idPut
import com.tezov.tuucho.core.domain.schema.common.IdSchema.Companion.idSourceOrNull
import com.tezov.tuucho.core.domain.schema.common.IdSchema.Companion.idValueOrNull
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import org.koin.core.component.inject

class IdRectifier : Rectifier() {

    private val idGenerator: IdGenerator by inject()

    override val matchers: List<MatcherProtocol> by inject(
        Name.Matcher.ID
    )

    override fun beforeAlterNull(path: JsonElementPath, element: JsonElement) =
        mutableMapOf<String, JsonElement>().apply {
            val (id, idFrom, idAutoGenerated) = rectifyIds(null, null)
            idPut(id, idFrom, idAutoGenerated)
        }.let(::JsonObject)

    override fun beforeAlterPrimitive(
        path: JsonElementPath,
        element: JsonElement
    ) = mutableMapOf<String, JsonElement>().apply {
        val (id, idFrom, idAutoGenerated) = rectifyIds(element.find(path).stringOrNull, null)
        idPut(id, idFrom, idAutoGenerated)
    }.let(::JsonObject)

    override fun beforeAlterObject(path: JsonElementPath, element: JsonElement) =
        element.find(path).jsonObject.toMutableMap().apply {
            val (id, idFrom, idAutoGenerated) = rectifyIds(idValueOrNull, idSourceOrNull)
            idPut(id, idFrom, idAutoGenerated)
        }.let(::JsonObject)

    private fun rectifyIds(id: String?, idFrom: String?): Triple<String, String?, Boolean> {
        if (id == null || id.startsWith(SymbolData.ID_REF_INDICATOR)) {
            return Triple(
                idGenerator.generate(),
                id?.removePrefix(SymbolData.ID_REF_INDICATOR),
                true
            )
        }
        return Triple(id, idFrom?.removePrefix(SymbolData.ID_REF_INDICATOR), false)
    }
}