package com.tezov.tuucho.core.data.repository.parser.rectifier.id

import com.tezov.tuucho.core.data.repository.di.MaterialRectifierModule.Name
import com.tezov.tuucho.core.data.repository.parser.rectifier._system.AbstractRectifier
import com.tezov.tuucho.core.data.repository.parser.rectifier._system.MatcherRectifierProtocol
import com.tezov.tuucho.core.domain.business.jsonSchema._system.SymbolData
import com.tezov.tuucho.core.domain.business.jsonSchema._system.withScope
import com.tezov.tuucho.core.domain.business.jsonSchema.material.IdSchema
import com.tezov.tuucho.core.domain.business.protocol.IdGeneratorProtocol
import com.tezov.tuucho.core.domain.tool.annotation.TuuchoExperimentalAPI
import com.tezov.tuucho.core.domain.tool.json.JsonElementPath
import com.tezov.tuucho.core.domain.tool.json.find
import com.tezov.tuucho.core.domain.tool.json.stringOrNull
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import org.koin.core.component.inject

@OptIn(TuuchoExperimentalAPI::class)
class IdRectifier(
    private val idGenerator: IdGeneratorProtocol
) : AbstractRectifier() {
    override val matchers: List<MatcherRectifierProtocol> by inject(
        Name.Matcher.ID
    )

    override fun beforeAlterNull(
        path: JsonElementPath,
        element: JsonElement,
    ) = JsonNull
        .withScope(IdSchema::Scope)
        .apply {
            val (value, source, idAutoGenerated) = rectifyIds(null, null)
            this.value = value
            source?.let { this.source = it }
            idAutoGenerated?.let { this.idAutoGenerated = it }
        }.collect()

    override fun beforeAlterPrimitive(
        path: JsonElementPath,
        element: JsonElement,
    ) = element
        .find(path)
        .withScope(IdSchema::Scope)
        .apply {
            val (value, source, idAutoGenerated) = rectifyIds(
                this.element.stringOrNull,
                null
            )
            this.value = value
            source?.let { this.source = it }
            idAutoGenerated?.let { this.idAutoGenerated = it }
        }.collect()

    override fun beforeAlterObject(
        path: JsonElementPath,
        element: JsonElement,
    ) = element
        .find(path)
        .withScope(IdSchema::Scope)
        .apply {
            val (value, source, idAutoGenerated) = rectifyIds(
                this.value,
                this.source
            )
            this.value = value
            source?.let { this.source = it }
            idAutoGenerated?.let { this.idAutoGenerated = it }
        }.collect()

    private fun rectifyIds(
        id: String?,
        idFrom: String?
    ): Triple<String, String?, Boolean?> {
        if (id == null || id.startsWith(SymbolData.ID_REF_INDICATOR)) {
            return Triple(
                idGenerator.generate(),
                id?.removePrefix(SymbolData.ID_REF_INDICATOR),
                true
            )
        }
        return Triple(id, idFrom?.removePrefix(SymbolData.ID_REF_INDICATOR), null)
    }
}
