@file:Suppress("ktlint:standard:package-name")

package com.tezov.tuucho.core.data.repository.parser.rectifier._system

import com.tezov.tuucho.core.domain.business.jsonSchema._system.OpenSchemaScope
import com.tezov.tuucho.core.domain.business.jsonSchema._system.withScope
import com.tezov.tuucho.core.domain.business.jsonSchema.material.ComponentSchema
import com.tezov.tuucho.core.domain.business.jsonSchema.material.IdSchema
import com.tezov.tuucho.core.domain.business.jsonSchema.material.IdSchema.addGroup
import com.tezov.tuucho.core.domain.business.jsonSchema.material.IdSchema.hasGroup
import com.tezov.tuucho.core.domain.business.jsonSchema.material.SubsetSchema
import com.tezov.tuucho.core.domain.tool.json.JsonElementPath
import com.tezov.tuucho.core.domain.tool.json.findOrNull
import kotlinx.serialization.json.JsonElement

object RectifierHelper {
    fun <T : OpenSchemaScope<T>> OpenSchemaScope<T>.rectifyIds(
        defaultGroup: String
    ): Pair<String?, String?> {
        var valueRectified: String?
        var sourceRectified: String?
        onScope(IdSchema::Scope).apply {
            valueRectified = value
                ?.takeIf { !it.hasGroup() && idAutoGenerated != true }
                ?.addGroup(defaultGroup)
            sourceRectified = source
                ?.takeIf { !it.hasGroup() }
                ?.addGroup(defaultGroup)
        }
        return valueRectified to sourceRectified
    }

    fun retrieveSubsetOrMarkUnknown(
        path: JsonElementPath,
        element: JsonElement,
    ) = element
        .findOrNull(path.parent())
        ?.withScope(ComponentSchema::Scope)
        ?.subset
        ?: SubsetSchema.Value.unknown
}
